version: 0.2

phases:
  install:
    commands:
      - npm install --force
      - npm install react-scripts@latest --save

  build:
    commands:
      - npm run build  # Builds the project
artifacts:
  files:
    - '**/*'
  base-directory: build  # Directory with output files (e.g., React app)